### ISSUE TITLE
Table not rendering

### ISSUE THREAD

**Issue by olufemioyedepo** [bhaveshpatel200/vue3-datatable-document#1]
Hi @bhaveshpatel200, good day.
This datatable library looks great but I've not been able to get it to work.

After following the basic usage example here => https://vue3-datatable-document.vercel.app/

![image](https://user-images.githubusercontent.com/19518859/225032128-fea3990f-6eec-426d-b07f-0bd957295d27.png)
![image](https://user-images.githubusercontent.com/19518859/225032423-43729aea-4d6d-4e46-aa54-c06071b755ce.png)

![image](https://user-images.githubusercontent.com/19518859/225032925-785b9ec8-d315-4371-9168-8ab0c13eda53.png)

Kindly help

**Comment by bhaveshpatel200** [comment]
Hi,
Can you please let me know exact version of VueJS or NuxtJS ?
and if possible then can you please send me your sample project, so I can figure out exactly what's a problem. 
IF you got any error in console then please send error also.

**Comment by olufemioyedepo** [comment]
"vue": "3.2.39"

**Comment by bhaveshpatel200** [comment]
OK, can you please provide demo ?
Have you follow all the steps including install package and import package and css in page. i think you missing anything from that.

**Comment by olufemioyedepo** [comment]
it works now!
![image](https://user-images.githubusercontent.com/19518859/225154196-2830f7ba-e45b-4b56-be64-ffad3905dd0d.png)

I forgot to add this => export default {
    name: 'StudentsListing',
    **components: {
        Vue3Datatable
    }**,

**Comment by olufemioyedepo** [comment]
@bhaveshpatel200 this is a good library, please do not let it die.
I will try and contribute in my spare time, cheers!

**Comment by bhaveshpatel200** [comment]
Thanks.
This library is always alive.
I will add more features soon like server side pagination, grouping etc.
