### ISSUE TITLE
export data in csv or other format

### ISSUE THREAD

**Issue by clauestay** [bhaveshpatel200/vue3-datatable-document#17]
You could add the option to export the data or if it is already possible, add how to do it

**Comment by bhaveshpatel200** [comment]
Hi,

We are not providing any export functionality in this package. but can write simple export csv export code to export all data. we are providing methods where you can get filtered rows or selected rows whatever you want to export based on that.

Its easy to add export csv, i will try to upload new demo with export functionality this weekend.

**Comment by clauestay** [comment]
Thank you very much for responding, I will be aware if you upload the code you mention

**Comment by bhaveshpatel200** [comment]
Hi clauestay,

I have added export example, you can find from the below link:
https://vue3-datatable-document.vercel.app/export
