### ISSUE TITLE
Can't find the row index

### ISSUE THREAD

**Issue by marufhasan1** [bhaveshpatel200/vue3-datatable-document#18]
Is there any way to get the row index on any of the column's slots?

**Comment by bhaveshpatel200** [comment]
Hi,

You can get only row data which is passed in rows. you can use **id** instead of **row index** if possible. as not sure what's your use case.

**Comment by sahilbhardwaj1** [comment]
Hi, have a use case when se delete the record after the success, we splice the item according to the index. We don't need to find the index of deleted item. 

`const deleteCategory = async (data, index) => {
  const confirmed = await showDeleteConfirmation();
  if (confirmed) {
    const R = await UseCategory.deleteCategory(data._id);
    if (R.status) {
      categoryList.value.splice(index, 1);
    }
  } else {
    console.log("Delete canceled");
  }
};`

**Comment by bhaveshpatel200** [comment]
Hi [sahilbhardwaj1](https://github.com/sahilbhardwaj1)

I suggest that you need to refresh api after delete records, so always latest updated records will be reflected in table.
