### ISSUE TITLE
Custom function not working on cellRenderer

### ISSUE THREAD

**Issue by olufemioyedepo** [bhaveshpatel200/vue3-datatable-document#2]
![image](https://user-images.githubusercontent.com/19518859/225365307-60d2a51e-734d-447e-8fda-4998eeb81958.png)

const deactivateStudentAccount = () => {
            console.log('deactivateStudentAccount');
        };
The button @click does not call the deactivateStudentAccount function.
@bhaveshpatel200 any tip?

**Comment by bhaveshpatel200** [comment]
HI,
Can you please check Slot demo.
https://vue3-datatable-document.vercel.app/actions
you can easily display button conditions wise or can do anything in slot.

**Comment by bhaveshpatel200** [comment]
Hi,
For **cellrenderer**, it will be supports **functions** or **string** (cellRenderer?: [Function, string]).
Seems you are trying to add vue @click event in cellrenderer which is not working here its only support html. so alternative you can use slot which is best for you to add custom button or whatever you want in that.

**Comment by olufemioyedepo** [comment]
This works @bhaveshpatel200 , thanks!
