### ISSUE TITLE
How can I select some checkboxes from different pages when mounting the component?

### ISSUE THREAD

**Issue by alonsofc** [bhaveshpatel200/vue3-datatable-document#20]
My scenario is that I have a list of permissions for a user, when entering the user details, I want to display all the permissions available in the system and select the checkboxes of the permissions assigned to the user. Currently I have 23 permissions available in the table, in a 5-item pagination, but the user has permissions assigned that are on different pages of the table.

My current form:
![image](https://github.com/user-attachments/assets/a2d9390a-db01-479a-9ef0-63af50c88d1f)

What I need when the user permissions detail is opened:
![image](https://github.com/user-attachments/assets/abe31f5e-8fd1-4d4c-9b7e-81e556b42e1a)

![image](https://github.com/user-attachments/assets/0889738e-c322-42b5-96e8-f335536fda4e)

![image](https://github.com/user-attachments/assets/8772db05-fa98-4013-a38b-55ab9d0ee3f7)

And so on on all the pages...

I don't see any examples on your page with that use case.

Next I need to get all the rows that have been selected from all the pages and then save the user permissions in the database.

I look forward to your prompt help. Thank you.

**Comment by alonsofc** [comment]
For now I implemented it like this, but if anyone knows of a better, more native way, I'd appreciate it:

### **In the template:**
```
<vue3-datatable
    ref="datatable"
    :rows="permissionsList"
    :columns="dtColumns"
    :pageSize="5"
    :showPageSize="false"
    :hasCheckbox="true"
    @pageChange="pageChange">
</vue3-datatable>
```
### **In the script:**
```
const permissionsList = ref([]);
const selectedPermissions = ref([]);
const paginatedPermissions = ref([]);

const pageChange = (pageNumber) => {
    const startIndex = (pageNumber - 1) * dtParams.pagesize;
    const endIndex = startIndex + dtParams.pagesize;
    paginatedPermissions.value = permissionsList.value.slice(startIndex, endIndex);

    datatable.value.clearSelectedRows();

    selectedPermissions.value.forEach(permissionId => {
        const index = paginatedPermissions.value.findIndex((row) => row.id === permissionId);
        if (index !== -1)
            datatable.value.selectRow(index);
    });
};
```

**Comment by bhaveshpatel200** [comment]
Hi Alonso Fallas Calderón,

Sorry, this package does not provide row selection from multiple pages, rows will cleared when you paginate to another page.

If you want to remember selected rows from pagination, you can take one variables to push selected ids and removed when unselected, using this you can easily fullfill your requirements.

I think you can got event when checked/unchecked checkbox and maintain new variable.
