### ISSUE TITLE
unable to call getSelectedRows method

### ISSUE THREAD

**Issue by MayanSolutions** [bhaveshpatel200/vue3-datatable-document#4]
unable to get the selected rows which are checked in the checkbox

**Comment by MayanSolutions** [comment]
Figured it out, need the rowSelected event

**Comment by nizzam** [comment]
Hi @MayanSolutions 

Could you please share the code example.
I didnt get the idea on how to use methods.

_p/s: I'm still new with Vue3_

**Comment by FYILTD** [comment]
@nizzam 

create the below 

// Object for selected rows
let selected = ref([]);
// Function to select rows
const rowSelect = async (client: any) => {
  selected.value = JSON.parse(JSON.stringify(client));
}

Add the below to the table component

@rowSelect="rowSelect"

**Comment by nizzam** [comment]
Hi @FYILTD 

Thank you for your response. Really appreciate it.

But, I'm referring to the [documentation](https://github.com/bhaveshpatel200/vue3-datatable#methods) provided, as screenshot below :

![Screenshot 2023-08-09 at 9 34 55 AM](https://github.com/bhaveshpatel200/vue3-datatable-document/assets/15359050/48ad54bb-aea4-4aeb-84d3-2cb1724b5cdd)

Hope you able to share a way of implementation and usage of those methods.

**Comment by bhaveshpatel200** [comment]
@nizzam 
I will add one more example with all events and methods by tomorrow.

**Comment by bhaveshpatel200** [comment]
@nizzam 
Please find the demo for all the methods with source code:
https://vue3-datatable-document.vercel.app/methods

**Comment by nizzam** [comment]
Hi @bhaveshpatel200 

Thank you very much for your prompt action.
Really appreciate it.

Wish you all the best !

**Comment by bhaveshpatel200** [comment]
Thanks..
