### ISSUE TITLE
unique filter item

### ISSUE THREAD

**Issue by fedottt** [bhaveshpatel200/vue3-datatable-document#7]
its me again)

is it possible make unique filter by column data?

in column i have some data like (printer, pc, pc, pc, hub, hub) and in select in header only unique (printer,pc,hub)

**Comment by fedottt** [comment]
and use only text from cell or some data-attr
in cell i have url like <a href="....">PC</a>

**Comment by bhaveshpatel200** [comment]
Hi,

It's up to you to what data you want to display like all data or unique etc. we have not this type any features.
and you can customize cell text using slots, so please check first all demos which covers all scenarios.

https://vue3-datatable-document.vercel.app/slot
