### ISSUE TITLE
Download data as a file

### ISSUE THREAD

**Issue by ruslanubaydullayev** [bhaveshpatel200/vue3-datatable-document#8]
Could you add this feature in this package? I think, it will be very usefull for all.

**Comment by bhaveshpatel200** [comment]
Ok, I will add export example soon.

**Comment by ruslanubaydullayev** [comment]
Hi,Bhavesh,  i cant find this feature in documentation, did you add to github?

**Comment by bhaveshpatel200** [comment]
Still not added, i will inform you once added exports examples.

**Comment by bhaveshpatel200** [comment]
Hi ruslanubaydullayev,

I have added export example, you can find from the below link:
https://vue3-datatable-document.vercel.app/export
