### ISSUE TITLE
Disable row checkbox click

### ISSUE THREAD

**Issue by Minotti** [bhaveshpatel200/vue3-datatable-document#9]
Hello there, can I disable row checkbox by a condition?

**Comment by bhaveshpatel200** [comment]
Hi Minotti,

Currently we have not any features like this but will think about in next updates. 
You can use custom checkbox using slots and add whatever conditions which will work for you.
OR 
You can also add conditionally class on row and apply css (**pointer-events: none**) on checkbox based on row class.
